name: amplify_user_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0
dependencies:
  amplify_auth_cognito_dart: ^0.11.3
  amplify_core: ^2.3.0
  amplify_secure_storage_dart: ^0.5.1
  password_dart: ^2.0.1
  uuid: ^4.4.2
